version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=45238
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=45238
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: